#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend  timmy-frontend
	bind *:80
	mode http
	default_backend timmy-backend
backend timmy-backend
	balance roundrobin
	server 92703-web-01 54.174.109.218:80 check
	server 92703-web-02 34.227.90.53:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
