#!/usr/bin/env bash
# delete the existing ../sites-enabled/default
# replace it with a copy of ../sites-available/default
# flag -s creates a symbolic link, -f deletes the existing file
# and replaces it
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
