#!/usr/bin/env bash
# displays To infinity and beyond indefinitely.

handle_sigterm() {
	echo "I hate the kill command"
	rm -rf /var/run/myscript.pid
	exit 0
}
handle_sigint() {
	echo "Y U no love me?!"
	exit 0
}
echo $$ > /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap handle_sigterm SIGTERM
	trap handle_sigint SIGINT
	trap 'rm -rf /var/run/myscript.pid; exit' SIGQUIT
done
