#!/usr/bin/env bash
# displays To infinity and beyond indefinitely.

handle_sigterm() {
	echo "I am invincible!!!"
}
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap handle_sigterm SIGTERM
done
